name: Deploy to EC2

on:
    push:
        branches:
            - main # or the branch you want to deploy

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  pip install awscli

            - name: Deploy to EC2
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
              run: |
                  echo "Running AWS SSM command..."
                  aws ssm send-command \
                    --document-name "AWS-RunShellScript" \
                    --targets "Key=instanceids,Values=i-074d998711dc172eb" \
                    --parameters 'commands=["cd /var/www/html/ecom_ && git pull origin main"]' \
                    --region ${{ secrets.AWS_REGION }} \
                    --query "Command.CommandId" \
                    --output text
                  echo "SSM Command issued."
