name: Deploy to CodeDeploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up AWS CLI
              uses: aws-actions/configure-aws-credentials@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Deploy to CodeDeploy
              run: |
                  aws deploy create-deployment \
                    --application-name scandiweb ins \
                    --deployment-group-name my-deployment-group \
                    --revision "{\"revisionType\":\"S3\",\"s3Location\":{\"bucket\":\"my-bucket\",\"key\":\"my-app.zip\",\"bundleType\":\"zip\"}}" \
                    --description "Deploying new version"
